version: '3.9'

services:
  frontend:
    build:
      context: ./projet-devops
      dockerfile: .dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
      - mysql
    networks:
      - education-network
    environment:
      - API_URL=http://api:80
      - DB_HOST=mysql
      - DB_PORT=3306

  api:
    build:
      context: ./DEVOPS-API
      dockerfile: .dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - education-network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=EDUCATION

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EDUCATION
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config:/docker-entrypoint-initdb.d
    command: --max_allowed_packet=1024M --innodb_buffer_pool_size=2G --default-authentication-plugin=mysql_native_password
    networks:
      - education-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: "1"
      UPLOAD_LIMIT: "300M"
      MAX_EXECUTION_TIME: "300"
      MEMORY_LIMIT: "512M"
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - education-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - education-network

  wave-scope:
    image: weaveworks/scope:1.13.2
    container_name: wave_scope
    restart: unless-stopped
    privileged: true
    pid: "host"
    ports:
      - "4040:4040"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys/kernel/debug:/sys/kernel/debug:ro
    environment:
      - SCOPE_HOSTNAME=wave_scope
    command:
      - "--probe.docker=true"
      - "--probe.docker.bridge=docker0"
      - "--probe.processes=true"
    networks:
      - education-network

networks:
  education-network:
    driver: bridge

volumes:
  mysql_data:
  portainer_data: